## Informação Mútua

In [1]:
#conta do valor de P(x,y) * log2 (P(x,y)/(P(x)*P(y)))
import math

def calcular_informacao_mutua(nx, ny, nyx, N):
    termo1 = (nx / N)
    termo2 = math.log2((nyx / N) / ((ny / N) * (nx / N)))

    elemento = termo1 + termo2
    return elemento

# Exemplo de uso
nx = 10  # número de ocorrências da variável X
ny = 20  # número de ocorrências da variável Y
nyx = 5  # número de ocorrências conjuntas de X e Y
N = 100  # número total de observações

resultado = calcular_informacao_mutua(nx, ny, nyx, N)
print(f"O valor da Informação Mútua é: {resultado}")


O valor da Informação Mútua é: 1.4219280948873623


In [2]:
import numpy as np
from scipy.stats import entropy

def calcular_informacao_mutua_total(contingency_table):
    # Calcular as probabilidades marginais
    marginais_x = np.sum(contingency_table, axis=1) / np.sum(contingency_table)
    marginais_y = np.sum(contingency_table, axis=0) / np.sum(contingency_table)

    # Calcular a probabilidade conjunta
    conjunta = contingency_table / np.sum(contingency_table)

    # Calcular a Informação Mútua total
    informacao_mutua_total = np.sum([conjunta[i, j] * np.log2(conjunta[i, j] / (marginais_x[i] * marginais_y[j]))
                                     for i in range(contingency_table.shape[0])
                                     for j in range(contingency_table.shape[1])
                                     if conjunta[i, j] > 0])

    return informacao_mutua_total

# Exemplo de uso com uma tabela de contingência
tabela_contingencia = np.array([[4, 4,9], [1, 2,1]])
resultado = calcular_informacao_mutua_total(tabela_contingencia)

print(f"A Informação Mútua total é: {resultado}")


A Informação Mútua total é: 0.04487743630674444


## Goodman Kruskal

In [3]:
tabela_contingencia = np.array([[6, 1], [2, 2]])
total = np.sum(tabela_contingencia)

Pe = 1 - np.max(np.sum(tabela_contingencia, axis=0))/total
print(Pe*11)
Pey = 1 - (np.max(tabela_contingencia[0])+np.max(tabela_contingencia[1]))/total

y = (Pe- Pey)/Pe
print(y)



3.0
0.0


## 2b recurso - Implementar KNN

In [4]:
from sklearn.neighbors import NearestNeighbors
import numpy as np

# Criar um conjunto de dados de exemplo
dados = np.array([[4, 5],
                  [3, 6],
                  [4, 8],
                  [8, 10],
                  [6, 1],
                  [18, 5],
                  [8, 16],
                  [3, 0],
                  [18, 18],
                  [19, 14],
                  [8, 9],
                  [2, 11],
                  [5, 4],
                  [8, 9],
                  [11, 19],
                  [5, 10],
                  [12, 10]])

# Especificar o número de vizinhos que você deseja encontrar
k_vizinhos = 5

# Ponto para o qual você quer encontrar os vizinhos mais próximos
ponto_teste = np.array([[10, 10]])

# Inicializar o modelo k-NN
modelo_vizinhos = NearestNeighbors(n_neighbors=k_vizinhos, algorithm='ball_tree')
modelo_vizinhos.fit(dados)

# Encontrar os vizinhos mais próximos para o ponto de teste
distancias, indices_vizinhos = modelo_vizinhos.kneighbors(ponto_teste)

# Exibir os resultados
print(f"Os {k_vizinhos} vizinhos mais próximos para o ponto {ponto_teste} são:")
for i in range(k_vizinhos):
    vizinho = dados[indices_vizinhos[0][i]]
    distancia = distancias[0][i]
    print(f"Vizinho {i + 1}: Ponto {indices_vizinhos[0][i]} - Distância: {distancia:.4f}")


Os 5 vizinhos mais próximos para o ponto [[10 10]] são:
Vizinho 1: Ponto 3 - Distância: 2.0000
Vizinho 2: Ponto 16 - Distância: 2.0000
Vizinho 3: Ponto 13 - Distância: 2.2361
Vizinho 4: Ponto 10 - Distância: 2.2361
Vizinho 5: Ponto 15 - Distância: 5.0000


## FDA

Determine a projeção que maximiza a separabilidade das duas classes C1 e C2,

In [5]:
C1= np.array([
    [4, 5], [3, 6], [4, 8], [8, 10], [6, 1], [18, 5], [8, 16], [3, 0],
    [18, 18], [19, 14], [8, 9], [2, 11], [5, 4], [8, 9], [11, 19], [5, 10],
    [12, 10], [14, 4], [4, 9], [2, 12], [28, 32], [22, 33], [22, 30],
    [34, 16], [15, 20]
])
C2 = np.array([[6, 2],
                [13, 14],
                [17, 21],
                [28, 28],
                [24, 18],
                [30, 15],
                [29, 29],
                [33, 25],
                [32, 24]])

#Cálculo das médias
u1 = np.mean(C1, axis=0)
u2 = np.mean(C2, axis=0)

#Matrizes de Covariância
E1 = np.zeros((2,2))
for i in C1:
    aux = (i - u1).reshape(-1, 1)
    E1 += np.dot(aux,aux.T)

E1 = E1/C1.shape[0]

E2 = np.zeros((2,2))
for i in C2:
    aux = (i - u2).reshape(-1, 1)
    E2 += np.dot(aux,aux.T)

E2 = E2/C2.shape[0]

#Matriz de Covariância
S=E1+E2

#w = S^(\1)*(U1-U2)
#S_1 = S/np.linalg.det(S)
S_1 = np.linalg.inv(S)
w = np.dot(S_1,(u1 - u2).reshape(-1, 1))
print(w)



[[-0.09547776]
 [ 0.02142844]]


## Nota:

A partir daqui é codigo do exame de template

## Calculo Entropias

In [6]:
import numpy as np

S = np.array([1, 1, 2, 2, 2, 1, 1, 2])

for i in range(1, len(S)):
    S1 = S[:i]
    S2 = S[i:]

    PY1 = np.sum(S1 == 1)
    PG1 = len(S1) - PY1
    x1 = np.array([PY1, PG1]) / len(S1)
    H1 = -np.sum(x1[x1 != 0] * np.log2(x1[x1 != 0]))

    PY2 = np.sum(S2 == 1)
    PG2 = len(S2) - PY2
    x2 = np.array([PY2, PG2]) / len(S2)
    H2 = -np.sum(x2[x2 != 0] * np.log2(x2[x2 != 0]))

    H = (len(S1) * H1 + len(S2) * H2) / len(S)

    print(f"i={i}: H1={H1}, H2={H2} => H={H}")


i=1: H1=-0.0, H2=0.9852281360342515 => H=0.8620746190299701
i=2: H1=-0.0, H2=0.9182958340544896 => H=0.6887218755408672
i=3: H1=0.9182958340544896, H2=0.9709505944546686 => H=0.9512050593046015
i=4: H1=1.0, H2=1.0 => H=1.0
i=5: H1=0.9709505944546686, H2=0.9182958340544896 => H=0.9512050593046015
i=6: H1=1.0, H2=1.0 => H=1.0
i=7: H1=0.9852281360342515, H2=-0.0 => H=0.8620746190299701


## Calculo da regressão linear de ordem 3

In [7]:
import numpy as np

# Dados de entrada
x = np.array([1, 1.69, 2.17, 2.30, 2.08, 1.65, 1.23, 1.63, 1.27, 1.87, 2.71, 3.59, 4.27, 4.62])

# Inicializando X e Y
X = np.empty((0, 4)) #X = np.empty((0, ordem + 1)) 
Y = np.empty((0, 1))

# Criando X e Y a partir dos dados
for i in range(3, len(x)):                #alterar o  3 para ordem
    X = np.vstack([X, [1, x[i-1], x[i-2], x[i-3]]]) #alterar o numero de colunas consoante a ordem
    Y = np.vstack([Y, [x[i]]])

# Resolvendo para os coeficientes beta
beta = np.linalg.lstsq(X, Y, rcond=None)[0]

# Exibindo a matriz X e os coeficientes beta
print("Matrix X:")
print(X)
print("\nCoefficients beta:")
print(beta)

# Estimando y(1.4)
x_new = np.array([1, x[-1], x[-2], x[-3]])  #alterar consoante a ordem
y_1_4 = np.dot(x_new, beta)

# Exibindo o valor estimado de y(1.4)
print("\nEstimated value of y(1.4):")
print(y_1_4)


Matrix X:
[[1.   2.17 1.69 1.  ]
 [1.   2.3  2.17 1.69]
 [1.   2.08 2.3  2.17]
 [1.   1.65 2.08 2.3 ]
 [1.   1.23 1.65 2.08]
 [1.   1.63 1.23 1.65]
 [1.   1.27 1.63 1.23]
 [1.   1.87 1.27 1.63]
 [1.   2.71 1.87 1.27]
 [1.   3.59 2.71 1.87]
 [1.   4.27 3.59 2.71]]

Coefficients beta:
[[ 0.52650708]
 [ 1.41766048]
 [-0.36667627]
 [-0.28318784]]

Estimated value of y(1.4):
[4.4937465]


## K-means

In [8]:
import numpy as np

# Definindo as coordenadas dos pontos
p = np.array([[x, c, v, b, n], [v, v, v, v], ...])  # Complete com as coordenadas reais

# Inicializando os centroides m1 e m2
m1 = np.random.rand(5, 1)  # Exemplo de inicialização aleatória
m2 = np.random.rand(5, 1)  # Exemplo de inicialização aleatória

for k in range(1, 6):
    p1 = np.empty((0, 5))
    p2 = np.empty((0, 5))

    for i in range(p.shape[0]):
        if np.sum((m1 - p[i, :])**2) < np.sum((m2 - p[i, :])**2):
            p1 = np.vstack([p1, p[i, :]])
        else:
            p2 = np.vstack([p2, p[i, :]])

    if p1.shape[0] > 0:
        m1 = np.mean(p1, axis=0)
    if p2.shape[0] > 0:
        m2 = np.mean(p2, axis=0)

    print(f"it: {k}")
    print("cluster 1:")
    print(p1)
    print("cluster 2:")
    print(p2)


NameError: name 'c' is not defined

## pca 

In [ ]:
import numpy as np

# Dados de entrada
x = np.array([22, 44, 55, ...])
w = np.array([22, 44, 55, ...])
y = np.array([22, 44, 55, ...])
z = np.array([22, 44, 55, ...])
t = np.array([22, 44, 55, ...])

# Normalização Z-score
x = (x - np.mean(x)) / np.std(x)
w = (w - np.mean(w)) / np.std(w)
y = (y - np.mean(y)) / np.std(y)
z = (z - np.mean(z)) / np.std(z)
t = (t - np.mean(t)) / np.std(t)

# Matriz de dados
P = np.column_stack((x, w, y, z, t))

# Calculando a matriz de covariância
M = np.dot(P.T, P)

print("Covariância:")
print(M)

# Decompõe em valores singulares (SVD)
U, W, V = np.linalg.svd(M)

print('U (primeiras colunas -> primeiros PCs):')
print(U)

print('W (valores próprios):')
print(W)

print('V (vetores próprios):')
print(V)
